version: 2
jobs:
  build:
    working_directory: ~/clj-noob
    docker:
      - image: clojure
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.04.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin      
      - run: which lein
      - run: lein deps
      - run: lein test
      - run:
          name: build and push
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t circleci/cci-demo-docker:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push circleci/cci-demo-docker:$TAG
