version: 2
jobs:
  build:
    working_directory: ~/clj-noob
    docker:
      - image: clojure
    steps:
      - checkout
      - run: lein deps
      - run: lein test
      - run: make build
      - run: make deploy-staging
        
